application: jsonp-sandbox
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/(.*)

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
